#pragma once

#define SLBINGOCORE_MAJOR_VERSION 0
#define SLBINGOCORE_MINOR_VERSION 1
#define SLBINGOCORE_PATCH_VERSION 0

#define VERSION_STRINGIFY(x) #x
#define VERSION_TO_STRING(x) VERSION_STRINGIFY(x)
#define SLBINGOCORE_VERSION VERSION_TO_STRING(SLBINGOCORE_MAJOR_VERSION) "." VERSION_TO_STRING(SLBINGOCORE_MINOR_VERSION) "." VERSION_TO_STRING(SLBINGOCORE_PATCH_VERSION)
